sudo: required
services:
  - docker

before_install:
  - docker build -t kiransheshadri858/docker-react -f  Dockerfile.dev .

script:
  - docker run kiransheshadri858/docker-react npm run test -- --coverage
