sudo: required
services:
  - docker

before_install:
  - docker build -t kiransheshadri858/docker-react -f  Dockerfile.dev .

script:
  - docker run -e CI=true kiransheshadri858/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-1-819506882356"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"